spring.application.name=stockglance


#custom port
server.port=9002


# prefix on url
server.servlet.context-path = /stockglance

# my sql connection
spring.datasource.url=jdbc:postgresql://localhost:5432/stockglance
spring.datasource.username=root
spring.datasource.password=ritik768
spring.datasource.driver-class-name=org.postgresql.Driver



# Turn Off spring boot banner
spring.main.banner-mode=off

# Reduce logging level . Set to warn
#logging.level.root = warn


#spring.security.basic.enabled=true
#spring.security.user.name=root
#spring.security.user.password=ritik768

logging.level.org.springframework.jdbc.datasource=DEBUG
logging.level.com.zaxxer.hikari=DEBUG